export const routes = [
  { path: '/', category: 'home', key: 'home' },
  { path: '/jpg-to-gif', category: 'image-to-gif', key: 'jpg-to-gif' },
  { path: '/png-to-gif', category: 'image-to-gif', key: 'png-to-gif' },
  { path: '/jpeg-to-gif', category: 'image-to-gif', key: 'jpeg-to-gif' },
  { path: '/photo-to-gif', category: 'image-to-gif', key: 'photo-to-gif' },
  { path: '/compress-gif', category: 'gif-optimization', key: 'compress-gif' },
  { path: '/no-watermark-gif-maker', category: 'image-to-gif', key: 'no-watermark-gif-maker' },
  { path: '/video-to-gif', category: 'video-to-gif', key: 'video-to-gif' },
  { path: '/mp4-to-gif', category: 'video-to-gif', key: 'mp4-to-gif' },
  { path: '/screen-recording-to-gif', category: 'video-to-gif', key: 'screen-recording-to-gif' },
  { path: '/image-to-mp4', category: 'video-tools', key: 'image-to-mp4' },
  { path: '/compress-mp4', category: 'video-tools', key: 'compress-mp4' },
  { path: '/crop-gif', category: 'gif-editing', key: 'crop-gif' },
  { path: '/gif-canvas', category: 'gif-editing', key: 'gif-canvas' },
  { path: '/add-text-to-gif', category: 'gif-editing', key: 'add-text-to-gif' },
  // New SEO Landing Pages
  { path: '/gif-maker', category: 'home', key: 'gif-maker' },
  { path: '/make-gif', category: 'home', key: 'make-gif' },
  { path: '/create-gif', category: 'home', key: 'create-gif' },
  { path: '/video-to-gif-converter', category: 'video-to-gif', key: 'video-to-gif-converter' },
  { path: '/mp4-to-gif-converter', category: 'video-to-gif', key: 'mp4-to-gif-converter' },
  { path: '/mov-to-gif', category: 'video-to-gif', key: 'mov-to-gif' },
  { path: '/webm-to-gif', category: 'video-to-gif', key: 'webm-to-gif' },
  { path: '/avi-to-gif', category: 'video-to-gif', key: 'avi-to-gif' },
  { path: '/mkv-to-gif', category: 'video-to-gif', key: 'mkv-to-gif' },
  { path: '/gif-cropper', category: 'gif-editing', key: 'gif-cropper' },
  { path: '/gif-resizer', category: 'gif-editing', key: 'gif-resizer' },
  { path: '/resize-gif', category: 'gif-editing', key: 'resize-gif' },
  { path: '/gif-text-editor', category: 'gif-editing', key: 'gif-text-editor' },
  { path: '/caption-gif', category: 'gif-editing', key: 'caption-gif' },
  { path: '/meme-generator', category: 'gif-editing', key: 'meme-generator' },
  { path: '/gif-to-mp4', category: 'video-tools', key: 'gif-to-mp4' },
];
