import { routes } from './routes.js';

const defaultOg = 'https://plotlake.com/og-image.png';

const related = (currentPath) => {
  const others = routes.map((r) => r.path).filter((p) => p !== currentPath);
  // Ensure at least 6 links; cycle if needed
  const picks = [];
  for (let i = 0; picks.length < 6; i++) {
    picks.push(others[i % others.length]);
  }
  return picks;
};

export const seoData = {
  '/': {
    title: 'GIF 制作器 - 图片/视频转 GIF/WebP/APNG，免费无水印 | Plotlake',
    description:
      '免费在线 GIF 制作器，支持图片、视频转 GIF/WebP/APNG。无水印、无需注册、本地浏览器处理保护隐私。一键优化 Twitter、Discord、Slack 等平台，HEIC/HEIF 自动转换。',
    h1: 'GIF 制作器（图片/视频转 GIF/WebP/APNG，免费无水印）',
    intro: [
      'Plotlake is a privacy-first animation maker that runs entirely in your browser. Drop JPG, PNG, WebP, HEIC/HEIF from iPhone, or MP4/WebM/MOV files, trim what you need, and generate crisp GIF, Animated WebP, or APNG without uploading to a server. No watermark, no signup, no hidden limits - just fast local processing powered by WebAssembly FFmpeg.',
      'Three simple workflows: Convert format to quickly export GIF, WebP, or APNG. Optimize for platform to auto-tune settings for Twitter, Discord, Slack, Telegram, or Email with recommended output formats. Fine-tune for full control over quality, compression, dithering, and advanced GIF options.',
      'We ship presets tuned for social media platforms: one-click optimization for X (Twitter), Discord (8MB), Slack (5MB), Telegram, and Email (2MB). Choose GIF for universal compatibility, Animated WebP for 60% smaller files, or APNG for lossless PNG quality. Everything is adjustable: dithering, loop count, compression palette sizes, and fill color for padding.',
      'Modern formats supported: drop entire folders to batch import image sequences sorted by filename. HEIC/HEIF photos from iPhone are converted automatically. Output to Animated WebP (smaller than GIF, great quality) or APNG (full PNG quality, best for text/UI) with a single click.',
      'Because processing is local, sensitive footage never leaves your device. The first video run downloads a cached ~30MB FFmpeg core; after that, frame extraction and encoding stay snappy. For images, per-frame delay controls and crossfade options keep loops smooth while maintaining detail.',
      'Built for creators: free forever, no watermarks, and instant downloads. Try image or video mode, pick a platform preset (Twitter, Discord, Slack, Telegram, Email), tweak advanced filters if you like, and share your animation anywhere.',
    ],
    features: [
      '100% browser-side - nothing uploads, perfect for privacy-sensitive clips.',
      'No watermark, no account, no paywall; exports stay clean by default.',
      'Modern outputs: Animated WebP (60% smaller than GIF) and APNG (lossless PNG quality).',
      'iPhone-ready input: HEIC/HEIF support + folder drop for batch import.',
      'Platform presets: One-click optimization for Twitter, Discord, Slack, Telegram, Email.',
      'Supports images (JPG, PNG, WebP, HEIC/HEIF) and video (MP4, WebM, MOV, AVI, MKV).',
      'Presets for Social, High Quality (4K, 100ms), Tutorial (crisp text), Small File.',
      'Customizable dithering (Bayer, Floyd-Steinberg, Sierra) and palette sizes.',
      'Limits tuned for stability: ~100MB images, ~60s or ~300 frames for video.',
      'Loop controls (infinite/finite), crossfade option, frame delay or FPS-based timing.',
      'Instant download links; FFmpeg core cached after first load.',
    ],
    faq: [
      { q: 'Is it really free and watermark-free?', a: 'Yes. All exports are free with no watermark or branding, no account required, no premium tier.' },
      { q: 'Do you upload my files?', a: 'No. Processing happens locally in your browser via WebAssembly FFmpeg, so files never leave your device.' },
      { q: 'What formats are supported?', a: 'Input: JPG, PNG, WebP, HEIC/HEIF, folders. Video: MP4, WebM, MOV, AVI, MKV. Output: GIF, Animated WebP, APNG.' },
      { q: 'Can I use HEIC photos from iPhone?', a: 'Yes! Drop HEIC/HEIF photos directly. They are converted to PNG automatically in your browser.' },
      { q: 'Can I drop a folder of images?', a: 'Yes! Drag a folder onto the upload area. Images are sorted by filename (natural order). Non-image files are ignored.' },
      { q: 'What is Animated WebP vs GIF?', a: 'Animated WebP is typically 60% smaller than GIF with better quality. Most modern browsers support it. GIF has universal compatibility.' },
      { q: 'What is APNG?', a: 'APNG (Animated PNG) preserves full PNG quality without 256-color limitations. Best for UI screenshots and text-heavy animations.' },
      { q: 'How do platform presets work?', a: 'Click Twitter, Discord, Slack, Telegram, or Email to apply optimized settings (width, delay, compression, format) for each platform.' },
      { q: 'How do I make smaller files?', a: 'Choose Small File preset, use Animated WebP format, reduce width, lower FPS, or pick Medium/Heavy compression.' },
      { q: 'Do presets change my files?', a: 'Presets only adjust settings (width, delay/FPS, loop, dithering, compression, format). Your originals stay untouched in-memory.' },
    ],
    relatedLinks: related('/'),
    ogImage: defaultOg,
  },
  '/jpg-to-gif': {
    title: 'JPG to GIF Converter | Free, No Watermark | Plotlake',
    description:
      'Convert JPG images to smooth GIFs online. No watermark, no signup, privacy-first browser processing. Use presets for social, tutorials, ultra quality, or small files.',
    h1: 'JPG to GIF Converter (Fast, Clean, No Watermark)',
    intro: [
      'Drop multiple JPG files and turn them into a single animated GIF without ever uploading to a server. Plotlake runs FFmpeg in your browser, so sensitive photos stay private while you tweak frame delay, width, and dithering.',
      'Use Social or High Quality presets for smooth loops, or Small File to hit size limits. The tool respects ~100MB total image guidance and offers Bayer, Floyd-Steinberg, or Sierra dithering for crisp gradients.',
      'Loop infinitely for social posts or set finite loops for tutorials. Add padding (black or white) to unify inconsistent sizes, and tune compression palettes between 64-256 colors to balance detail and weight.',
    ],
    features: [
      'Batch JPG upload with drag-and-drop and manual reorder.',
      'No watermark exports; free and browser-only.',
      'Presets: Social (2K/120ms), High Quality (4K/100ms), Tutorial (2K/160ms), Small File (HD/180ms).',
      'Custom frame delay, loop count, dithering, palette size, and fill color.',
      'Guidance: keep total JPG payload under ~100MB for stable processing.',
      'Instant GIF download; FFmpeg core cached after first use.',
    ],
    faq: [
      { q: 'Will JPG compression artifacts show in the GIF?', a: 'Artifacts in the source will carry over. Use High Quality preset or higher width to preserve more detail.' },
      { q: 'How many JPGs can I combine?', a: 'You can add many, but staying under ~100MB total keeps processing smooth in most browsers.' },
      { q: 'Do I need to register or pay?', a: 'No. It is free, watermark-free, and requires no signup.' },
      { q: 'Can I change per-frame timing?', a: 'Yes. Set a global delay or individual frame delays, and loop infinitely or a set number of times.' },
      { q: 'Is any data uploaded?', a: 'No. All processing stays in your browser; files never leave your device.' },
    ],
    relatedLinks: related('/jpg-to-gif'),
    ogImage: defaultOg,
  },
  '/png-to-gif': {
    title: 'PNG to GIF Converter | Preserve Transparency | Plotlake',
    description:
      'Turn PNG images into animated GIFs with preserved edges. Free, no watermark, browser-side processing. Presets for social, tutorials, ultra quality, and small files.',
    h1: 'PNG to GIF Converter (Transparency-Friendly, No Watermark)',
    intro: [
      'Upload transparent or opaque PNG files and stitch them into a clean GIF locally. Plotlake keeps your assets private and avoids server uploads while letting you set frame delays, loops, and dithering that respect transparency.',
      'Pick Social, High Quality, Tutorial, or Small File presets to balance smoothness and size. Bayer and Floyd-Steinberg dithering help avoid banding on gradients, while palette controls keep files light.',
      'Pad with black or white to normalize dimensions, or rely on quality presets (HD-4K) for crisp edges. Recommended total payload is under ~100MB for fast, stable browser processing.',
    ],
    features: [
      'Handles transparent PNGs with clean edges.',
      'Presets covering social, tutorials, ultra quality, and small file targets.',
      'Adjust frame delay, loop count, dithering, palette size, and padding color.',
      'No watermark, no signup, 100% browser-side.',
      'Instant downloads with cached FFmpeg core after first load.',
      'Guidance: stay under ~100MB total PNG size for smooth runs.',
    ],
    faq: [
      { q: 'Does PNG transparency stay intact?', a: 'GIF supports single-color transparency; edges remain clean when you choose appropriate dithering and padding.' },
      { q: 'Can I mix PNG and JPG?', a: 'Yes. Upload any mix; frames will be normalized to your selected size and padding.' },
      { q: 'What if my PNGs are huge?', a: 'Use 2K or HD presets, or reduce width manually to keep memory usage manageable.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are watermark-free by default.' },
      { q: 'Is it private?', a: 'Yes. All work is done locally in your browser.' },
    ],
    relatedLinks: related('/png-to-gif'),
    ogImage: defaultOg,
  },
  '/jpeg-to-gif': {
    title: 'JPEG to GIF Converter | Free & Private | Plotlake',
    description:
      'Convert JPEG photos to GIFs in your browser. No watermark, no signup, presets for quality or small files. Privacy-first: files never leave your device.',
    h1: 'JPEG to GIF Converter (Clean Exports, Browser-Only)',
    intro: [
      'Drop JPEG photos and combine them into a smooth GIF without uploading. Plotlake runs FFmpeg locally, letting you manage quality, delay, dithering, and compression while keeping content private.',
      'Choose High Quality for 4K sharpness, Social for balanced smoothness, Tutorial for crisp UI text, or Small File to hit weight targets. Width, padding, and palette settings let you control artifacts and size.',
      'Recommended limits: keep totals under ~100MB and frame delay between 100-180ms for fluid loops. Loop infinitely for socials or set finite loops for walkthroughs.',
    ],
    features: [
      'Batch JPEG handling with reorder controls.',
      'Presets tuned for quality vs. size trade-offs.',
      'Dithering options (Floyd, Sierra, Bayer) and palette control (64-256 colors).',
      'Padding color and width presets (HD-4K) to unify frames.',
      'No watermark, no signup, browser-side privacy.',
      'Instant download with cached FFmpeg core.',
    ],
    faq: [
      { q: 'Can I mix JPEG with PNG/WebP?', a: 'Yes. Mixed formats are normalized before GIF generation.' },
      { q: 'How do I avoid banding?', a: 'Use High Quality or Tutorial presets with Floyd/Sierra dithering and larger palettes.' },
      { q: 'Is there a size limit?', a: 'Stay under ~100MB total for best stability across browsers.' },
      { q: 'Do you store my images?', a: 'No. Everything runs locally; nothing is uploaded.' },
      { q: 'How do I keep loops smooth?', a: 'Use frame delays around 100-140ms or add more frames; crossfade can help for seamless loops.' },
    ],
    relatedLinks: related('/jpeg-to-gif'),
    ogImage: defaultOg,
  },
  '/photo-to-gif': {
    title: 'Photo to GIF Maker | Free Online | Plotlake',
    description:
      'Turn photos into animated GIFs online. Free, no watermark, browser-side processing with presets for social, tutorial, ultra quality, and small file outputs.',
    h1: 'Photo to GIF Maker (Fast, Private, No Signup)',
    intro: [
      'Upload photos from your phone or camera and create a GIF without any upload to a server. Plotlake processes everything in-browser, preserving privacy while giving you control over delay, width, dithering, and compression.',
      'Social and High Quality presets keep motion smooth and sharp; Tutorial keeps UI text crisp; Small File targets lightweight exports for messaging apps. Choose padding color to handle mixed aspect ratios and avoid cropping.',
      'Recommended payload: under ~100MB for best stability. Frame delays between 100-180ms produce fluid loops, and palette compression (64-256 colors) lets you choose quality vs. size.',
    ],
    features: [
      'Photo batches with drag-drop and reorder.',
      'Presets for social, tutorials, ultra quality, and small files.',
      'Dithering and palette controls to manage gradients and file weight.',
      'Padding color choices to avoid awkward cropping.',
      'No watermark, free to use, runs locally.',
      'Quick downloads once FFmpeg core is cached.',
    ],
    faq: [
      { q: 'Can I use HEIC photos?', a: 'Convert HEIC to JPG/PNG first; then upload. Most browsers decode JPG/PNG/WebP reliably.' },
      { q: 'What delay should I use?', a: '100-140ms for smooth motion, 160-200ms for slideshow-style beats.' },
      { q: 'How many photos are safe to add?', a: 'Dozens are fine; keep total size under ~100MB for performance.' },
      { q: 'Do you add branding?', a: 'No. GIFs export clean by default.' },
      { q: 'Is processing private?', a: 'Yes. Everything runs in your browser; no uploads occur.' },
    ],
    relatedLinks: related('/photo-to-gif'),
    ogImage: defaultOg,
  },
  '/compress-gif': {
    title: 'Compress GIF Online | Shrink Size, Keep Quality | Plotlake',
    description:
      'Compress GIF files without watermarks. Adjust palette and dithering to shrink size for Discord, Slack, or email. Privacy-first: processing stays in your browser.',
    h1: 'Compress GIF Without Watermarks (Browser-Only)',
    intro: [
      'Upload any GIF and reduce its size directly in your browser. Plotlake never uploads files, letting you tweak palette sizes, dithering, and optional resizing to hit size targets for Discord, Slack, or email.',
      'Use presets to aim for balance: Social and High Quality favor detail, while Small File trims color depth to 64-128 colors. Tutorial-style settings keep UI text legible for demo GIFs.',
      'Guidance: start with your original width, then reduce palette or width incrementally. All exports remain watermark-free and free to download.',
    ],
    features: [
      'Browser-side GIF compression; no uploads.',
      'Presets for quality vs. size, including Small File.',
      'Palette control (64-256 colors) and dithering choices.',
      'Optional resizing to HD/2K/4K widths.',
      'No watermark, no signup, free forever.',
      'Instant download after processing.',
    ],
    faq: [
      { q: 'How much can I shrink a GIF?', a: 'Typically 30-70% reduction by lowering palette size and width; results vary by content.' },
      { q: 'Will there be a watermark?', a: 'No. Exports are clean with no branding.' },
      { q: 'Do you upload my GIF?', a: 'No. Compression runs locally in your browser.' },
      { q: 'What settings reduce size the most?', a: 'Use Heavy compression (64 colors), lower width, and slower frame delays if acceptable.' },
      { q: 'Can I keep text sharp?', a: 'Use Tutorial preset or Floyd/Sierra dithering with light compression to maintain edges.' },
    ],
    relatedLinks: related('/compress-gif'),
    ogImage: defaultOg,
  },
  '/no-watermark-gif-maker': {
    title: 'No Watermark GIF Maker | Free Online | Plotlake',
    description:
      'Create GIFs without any watermark or branding. Free, no signup. Browser-only processing for images and videos with presets for quality and size.',
    h1: 'Make GIFs with Zero Watermarks (Free & Private)',
    intro: [
      'Build GIFs that stay clean - no logos, no "made with" tags. Plotlake processes images and videos locally, so nothing leaves your device and exports remain pristine.',
      'Pick a preset that matches your goal: High Quality for detail, Social for smooth sharing, Tutorial for crisp text, Small File for lightweight messaging. Adjust delay/FPS, dithering, palette, and padding color as needed.',
      'Guidance: keep image batches under ~100MB or videos under ~60s/300 frames to maintain speed. Download instantly once FFmpeg is cached.',
    ],
    features: [
      'Zero watermark or branding on exports.',
      'Presets for social, tutorials, ultra quality, and small files.',
      'Supports images (JPG/PNG/WebP) and videos (MP4/WebM/MOV/AVI/MKV).',
      'Browser-side privacy; no uploads.',
      'Palette, dithering, loop, and padding controls.',
      'Fast downloads with cached FFmpeg core.',
    ],
    faq: [
      { q: 'Do you ever add branding?', a: 'No. Watermark-free is the default for every export.' },
      { q: 'Is it really free?', a: 'Yes. There is no premium tier or signup requirement.' },
      { q: 'Are my files uploaded?', a: 'No. Processing stays in your browser, keeping media private.' },
      { q: 'Can I tune quality?', a: 'Yes. Adjust width, delay/FPS, dithering, compression, and padding to control quality and size.' },
      { q: 'Which preset should I start with?', a: 'Social for sharing, High Quality for detail, Tutorial for crisp text, Small File for tiny outputs.' },
    ],
    relatedLinks: related('/no-watermark-gif-maker'),
    ogImage: defaultOg,
  },
  '/video-to-gif': {
    title: 'Video to GIF Converter | Trim & Set FPS | Plotlake',
    description:
      'Convert video clips to GIF online. Supports MP4, WebM, MOV, AVI, MKV. Trim ranges, set FPS, use presets, and export watermark-free in your browser.',
    h1: 'Video to GIF Converter (Trim, FPS, No Watermark)',
    intro: [
      'Load a video (MP4/WebM/MOV/AVI/MKV), trim the exact range you need, and export a GIF without uploading to a server. Plotlake runs FFmpeg locally for privacy-first processing.',
      'Use Social (balanced), High Quality (24fps, 0 compression), Tutorial (10fps for crisp UI), or Small File (5fps, medium compression) presets to match your goal. Width presets align with HD-4K outputs.',
      'Recommended limits: clips under ~60 seconds or ~300 frames for reliable in-browser processing. Adjust dithering and palette size to reduce banding or shrink file weight.',
    ],
    features: [
      'Video formats: MP4, WebM, MOV, AVI, MKV (audio ignored for GIF).',
      'Trim start/end times and set FPS for smoothness or size.',
      'Presets for social, high quality, tutorials, and small files.',
      'Browser-side FFmpeg; no uploads; no watermark.',
      'Width presets (HD-4K) plus padding and dithering controls.',
      'Guidance: keep to ~60s/300 frames for speed; FFmpeg core cached after first load.',
    ],
    faq: [
      { q: 'What FPS should I pick?', a: '12-15 for most clips, 20-24 for very smooth motion, 5-8 for tiny files.' },
      { q: 'How long can my video be?', a: 'We suggest under ~60 seconds or ~300 frames to keep processing fast in-browser.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are clean with no branding.' },
      { q: 'Is my video uploaded?', a: 'No. Processing stays in your browser using WebAssembly FFmpeg.' },
      { q: 'How do I reduce file size?', a: 'Lower FPS, reduce width, shorten the clip, or choose Small File/medium compression.' },
    ],
    relatedLinks: related('/video-to-gif'),
    ogImage: defaultOg,
  },
  '/mp4-to-gif': {
    title: 'MP4 to GIF Converter | Free & Private | Plotlake',
    description:
      'Convert MP4 files to GIFs in-browser. Trim, set FPS, pick presets, and download watermark-free. Supports H.264/H.265 sources, no signup.',
    h1: 'MP4 to GIF Converter (Trim, Presets, No Watermark)',
    intro: [
      'Upload any MP4, trim the segment you need, and convert to a GIF without uploading to a server. Plotlake processes locally, keeping your footage private while offering FPS and width controls.',
      'Presets guide you: High Quality for detail, Social for balance, Tutorial for crisp UI text, Small File for lightweight sharing. Adjust palette/dithering to minimize banding.',
      'For stability, keep clips under ~60 seconds or ~300 frames. After the first FFmpeg load (~30MB cached), conversions speed up.',
    ],
    features: [
      'MP4 input with H.264/H.265 compatibility across modern browsers.',
      'Trim start/end and set FPS for smoothness vs. size.',
      'Presets spanning quality to small-file outcomes.',
      'No watermark, no signup; fully browser-side.',
      'Width presets (HD-4K) and palette/dither controls.',
      'Quick downloads once FFmpeg core is cached.',
    ],
    faq: [
      { q: 'What max size is recommended?', a: 'Stay under ~200MB and ~60s for best reliability; larger may strain memory.' },
      { q: 'Can I keep audio?', a: 'GIFs are silent; audio is ignored during conversion.' },
      { q: 'How do I make it smaller?', a: 'Lower FPS to 5-10, reduce width, or choose Small File/medium compression.' },
      { q: 'Is it private?', a: 'Yes. Files remain on your device; processing is local.' },
      { q: 'Do you add branding?', a: 'No. Exports are watermark-free by default.' },
    ],
    relatedLinks: related('/mp4-to-gif'),
    ogImage: defaultOg,
  },
  '/screen-recording-to-gif': {
    title: 'Screen Recording to GIF | Tutorial-Ready | Plotlake',
    description:
      'Convert screen recordings to GIFs for tutorials and demos. Trim, set FPS, pick presets, and keep text crisp. Free, no watermark, browser-side processing.',
    h1: 'Screen Recording to GIF (Crisp Text, No Watermark)',
    intro: [
      'Turn your screen recordings into shareable GIFs without uploading anywhere. Plotlake keeps text and UI elements sharp with tutorial-friendly presets and dithering choices.',
      'Import MP4/WebM/MOV/AVI/MKV captures, trim to the exact segment, and set FPS (10-15 often enough for UI). Use Tutorial preset for legible text, or High Quality for smoother motion.',
      'Guidance: keep clips under ~60 seconds or ~300 frames for quick in-browser processing. Palette and compression controls help hit size targets for docs, tickets, and chat tools.',
    ],
    features: [
      'Optimized for UI recordings with crisp text preservation.',
      'Presets for tutorials, socials, high quality, and small files.',
      'Trim ranges, set FPS, and choose width presets (HD-4K).',
      'No watermark; free; browser-only FFmpeg processing.',
      'Palette/dithering controls to reduce banding on gradients and UI overlays.',
      'Fast downloads once FFmpeg core is cached.',
    ],
    faq: [
      { q: 'What FPS works for UI demos?', a: '10-15 FPS usually keeps UI smooth; raise FPS for animation-heavy flows.' },
      { q: 'How do I keep text sharp?', a: 'Use Tutorial preset, higher width (HD/2K), and Floyd/Sierra dithering with light compression.' },
      { q: 'Is there a time limit?', a: 'Stay under ~60s/300 frames for reliable in-browser processing.' },
      { q: 'Are files uploaded?', a: 'No. Processing happens locally; nothing leaves your device.' },
      { q: 'Do you add branding?', a: 'No. Exports are watermark-free.' },
    ],
    relatedLinks: related('/screen-recording-to-gif'),
    ogImage: defaultOg,
  },
  '/image-to-mp4': {
    title: 'Image to MP4 Converter | Free Online, No Watermark',
    description:
      'Turn images into MP4 online for free. Smooth playback, fast processing, and clear limits with privacy notes.',
    h1: 'Image to MP4 Converter',
    categoryLabel: 'Video Tools',
    intro: [
      'Upload JPG, PNG, or WebP frames and render them into a smooth MP4 video without uploads or watermarks. Plotlake runs FFmpeg in the browser, so sensitive drafts stay on-device while you adjust FPS, per-frame duration, and padding color.',
      'Quick presets cover Social (720p, 24 fps), Tutorial (1080p, 15 fps), Small File (720p, 12 fps), and Ultra Quality (1080p, 30 fps). You can still override resolution (auto/720p/1080p), choose black or white padding to normalize aspect ratios, and set durations from 0.2–2 seconds per image.',
      'H.264 output with yuv420p and faststart ensures compatibility on phones, web embeds, and social platforms. Because the engine is cached after the first ~30MB load, subsequent runs are fast—even for longer slideshows.',
      'Recommended limits: stay under ~100MB of source images and a few hundred frames for best stability in-browser. If you hit errors, lower resolution, reduce FPS, or trim the sequence length.',
    ],
    sections: [
      { title: 'High-quality MP4 from images', body: 'Batch JPG/PNG/WebP, reorder frames, and render to balanced 720p/1080p outputs with padding that preserves composition.' },
      { title: 'Smooth playback on any platform', body: 'Encodes H.264 MP4 with yuv420p and faststart for shareable, stream-friendly playback everywhere.' },
      { title: 'Free to use, no sign-up required', body: 'No account, no watermark, and the first load caches FFmpeg so later exports are instant.' },
      { title: 'Privacy-first processing', body: 'Everything runs locally in your browser—nothing uploads—ideal for sensitive demos or drafts.' },
      { title: 'Clear limits (no surprises)', body: 'Best under ~100MB and a few hundred frames; lower FPS/resolution if your device struggles.' },
    ],
    features: [
      'Convert JPG/PNG/WebP sequences to MP4 with reorder controls.',
      'Presets: Social (720p, 24 fps), Tutorial (1080p, 15 fps), Small File (720p, 12 fps), Ultra (1080p, 30 fps).',
      'Duration per image from 0.2–2s plus global FPS controls (12–30 or Auto).',
      'Auto, 720p, or 1080p outputs with black/white padding to handle mixed aspect ratios.',
      'Outputs H.264 MP4 (yuv420p) with faststart for reliable sharing and embedding.',
      '100% browser-side FFmpeg, cached after first load; no watermark or signup.',
      'Guidance: keep total sources under ~100MB and a few hundred frames for stability.',
      'Designed for social posts, tutorials, slideshows, and lightweight motion graphics.',
      'Clear error guidance: lower resolution/FPS or reduce frame count if memory is tight.',
    ],
    faq: [
      { q: 'Is it free?', a: 'Yes. Free to use with no watermark or account.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are clean MP4 files without branding.' },
      { q: 'Do I need to sign up?', a: 'No signup or login—everything runs in your browser.' },
      { q: 'Do you upload my files?', a: 'No. Images stay on-device and are processed locally via WebAssembly FFmpeg.' },
      { q: 'What image formats are supported?', a: 'JPG, PNG, and WebP work best. You can mix formats in one sequence.' },
      { q: 'What are the limits (file size / number of images)?', a: 'For stability, keep total sources under ~100MB and a few hundred frames.' },
      { q: 'Why is it slow?', a: 'The first run downloads FFmpeg (~30MB). Large images or 1080p/30fps settings take longer to encode.' },
      { q: 'Why did export fail?', a: 'Try fewer images, lower FPS/duration, or 720p instead of 1080p to reduce memory use.' },
      { q: 'How to make smaller videos?', a: 'Use the Small File preset (720p, 12 fps, 0.5s) or shorten the frame list.' },
    ],
    relatedLinks: related('/image-to-mp4'),
    ogImage: defaultOg,
  },
  '/compress-mp4': {
    title: 'Compress MP4 Online | Free Video Compressor',
    description:
      'Compress MP4 online for free. Choose quality or resolution to shrink videos fast with clear limits and privacy notes.',
    h1: 'Compress MP4 Online',
    categoryLabel: 'Video Tools',
    intro: [
      'Upload an MP4 and shrink its size in the browser using quality (CRF) or resolution presets. Plotlake outputs H.264 MP4 with AAC audio and faststart enabled for instant playback, no watermark, and no signup.',
      'Quality modes map to Light/Medium/Heavy so you can pick balanced, smaller, or smallest files. Resolution options (Keep/1080p/720p/480p) maintain aspect ratio with even dimensions for maximum compatibility.',
      'Because everything runs locally with WebAssembly FFmpeg, videos never leave your device. The first load caches the ~30MB engine, keeping subsequent compressions quick—even on repeated runs.',
      'For stability, aim for clips under ~60 seconds. If you see errors, drop to 720p/480p or switch to Heavy compression to reduce memory and bitrate demands.',
    ],
    sections: [
      { title: 'Shrink MP4 file size fast', body: 'One-click Light/Medium/Heavy modes plus resolution targets make reliable reductions without guesswork.' },
      { title: 'Choose quality or resolution', body: 'CRF-based quality plus Keep/1080p/720p/480p scaling preserves aspect ratio and ensures even dimensions.' },
      { title: 'Free to use, no sign-up required', body: 'No account, no watermark—export clean MP4 files ready for sharing.' },
      { title: 'Privacy-first processing', body: 'Compression runs locally in your browser; nothing uploads to a server.' },
      { title: 'Clear limits (no surprises)', body: 'Best results for clips under ~60s. Lower resolution or pick Heavy if memory or time is tight.' },
    ],
    features: [
      'MP4 input with optional support for most H.264 sources (MOV/WebM may work depending on codec).',
      'Light, Medium, Heavy modes mapped to sensible CRF values for predictable size trade-offs.',
      'Resolution targets: Keep, 1080p, 720p, or 480p with aspect-ratio aware scaling.',
      'Outputs H.264 + AAC, yuv420p, faststart enabled for web-friendly playback.',
      'Browser-only FFmpeg; private, no upload or watermark.',
      'Guidance and fallbacks when errors happen: lower resolution or heavier preset.',
      'Progress feedback (loading engine, encoding, finalizing) with clear status text.',
      'Shows before/after size and reduction percentage for quick validation.',
    ],
    faq: [
      { q: 'Is it free?', a: 'Yes. Free to use with no watermark or signup.' },
      { q: 'Do you add a watermark?', a: 'No branding or watermark is added to your MP4.' },
      { q: 'Do you upload my video?', a: 'No. Compression runs locally in your browser using WebAssembly FFmpeg.' },
      { q: 'Why does quality drop?', a: 'Heavier CRF values trade detail for size. Use Light or Keep resolution for higher quality.' },
      { q: 'Which preset should I use?', a: 'Light for balance, Medium for smaller files, Heavy for the smallest size. Combine with 720p/480p if needed.' },
      { q: 'What are the limits?', a: 'Best under ~60 seconds for stability. Large files may need lower resolutions to avoid memory issues.' },
      { q: 'Why is it slow?', a: 'First run downloads FFmpeg (~30MB). High resolutions and longer clips take more time to encode in-browser.' },
      { q: 'Why did compression fail?', a: 'Try Heavy + 720p/480p, or shorten the clip before uploading to reduce memory and CPU load.' },
      { q: 'How to get smaller files?', a: 'Pick Heavy, drop to 720p/480p, and avoid very high-bitrate sources when possible.' },
    ],
    relatedLinks: related('/compress-mp4'),
    ogImage: defaultOg,
  },
  '/crop-gif': {
    title: 'Crop GIF Online | Free, No Watermark | Plotlake',
    description:
      'Crop animated GIFs, WebP, APNG, or videos locally in your browser. Free, no watermark, no upload. Select any region with aspect ratio presets.',
    h1: 'Crop GIF Online (Free, No Watermark)',
    categoryLabel: 'GIF Editing',
    intro: [
      'Crop animated GIFs, WebP, APNG, or video files directly in your browser without uploading to any server. Plotlake uses FFmpeg WebAssembly to process files locally, ensuring your content stays private.',
      'Select any crop region with drag handles, use preset aspect ratios (1:1, 4:3, 16:9, 9:16), and export to GIF, WebP, or MP4. Perfect for removing unwanted borders, focusing on specific content, or preparing animations for social media.',
      'All processing happens locally with no file uploads. The first run downloads a cached ~30MB FFmpeg core; subsequent crops are fast. No watermarks, no signup required.',
    ],
    features: [
      'Crop GIF, WebP, APNG, and MP4/WebM files locally.',
      'Interactive crop region with drag handles.',
      'Aspect ratio presets: Free, 1:1, 4:3, 16:9, 9:16.',
      'Output to GIF, WebP, or MP4 format.',
      'Two-pass GIF encoding for high quality.',
      'No watermark, no signup, 100% browser-side.',
      'Privacy-first: files never leave your device.',
    ],
    faq: [
      { q: 'What file formats can I crop?', a: 'GIF, WebP, APNG, MP4, and WebM files are supported.' },
      { q: 'Will cropping increase file size?', a: 'Usually cropping reduces file size since there are fewer pixels. Re-encoding may cause slight variations.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are completely watermark-free.' },
      { q: 'Are files uploaded to a server?', a: 'No. All processing happens locally in your browser using FFmpeg WebAssembly.' },
      { q: 'Why is processing slow?', a: 'First use downloads the ~30MB FFmpeg engine. Larger files and higher resolutions take more time.' },
      { q: 'Can I keep the original aspect ratio?', a: 'Yes, select "Free" ratio mode to crop to any custom region.' },
    ],
    relatedLinks: related('/crop-gif'),
    ogImage: defaultOg,
  },
  '/gif-canvas': {
    title: 'GIF Canvas / Pad | Resize Without Cropping | Plotlake',
    description:
      'Add padding to GIFs without cropping content. Resize canvas, choose alignment and background color. Free, no watermark, browser-only processing.',
    h1: 'GIF Canvas / Pad (Add Padding Without Cropping)',
    categoryLabel: 'GIF Editing',
    intro: [
      'Resize your GIF canvas without cropping any content. Add padding around your animation to fit specific dimensions like 512×512 for emojis, or standard video sizes like 1920×1080.',
      'Choose from preset canvas sizes or enter custom dimensions. Align your content anywhere on the canvas with 9-position alignment (corners, edges, center). Select transparent or solid color backgrounds.',
      'Unlike cropping, canvas expansion preserves all original content while adding space around it. Perfect for formatting GIFs for specific platforms, creating borders, or centering content.',
    ],
    features: [
      'Expand canvas without cropping original content.',
      'Preset sizes: 512×512, 640×640, 800×800, 1280×720, 1920×1080.',
      '9-position alignment grid for precise placement.',
      'Transparent or solid color backgrounds.',
      'Output to GIF, WebP, or MP4 format.',
      'No watermark, no signup, 100% browser-side.',
      'Privacy-first: files never leave your device.',
    ],
    faq: [
      { q: "What's the difference between Canvas and Crop?", a: 'Crop removes content outside the selection. Canvas only expands the canvas size and adds padding, keeping all original content intact.' },
      { q: 'Why would I use Canvas?', a: 'Common uses include formatting GIFs for specific platform requirements (like 512×512 for Discord emojis), adding decorative borders, or centering content.' },
      { q: 'Which formats support transparency?', a: 'GIF and WebP support transparent backgrounds. MP4 does not support transparency and will use a solid color.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are completely watermark-free.' },
      { q: 'Are files uploaded to a server?', a: 'No. All processing happens locally in your browser.' },
      { q: 'Will file size increase?', a: 'Yes, larger canvas dimensions typically increase file size, though the amount depends on the background type and padding area.' },
    ],
    relatedLinks: related('/gif-canvas'),
    ogImage: defaultOg,
  },
  '/add-text-to-gif': {
    title: 'Add Text to GIF | Free Caption & Meme Maker | Plotlake',
    description:
      'Add text, captions, or meme text to GIFs locally. Customize font size, color, stroke, and position. Free, no watermark, browser-only processing.',
    h1: 'Add Text to GIF (Captions, Memes, Watermarks)',
    categoryLabel: 'GIF Editing',
    intro: [
      'Add text overlays to your GIFs directly in the browser without uploading to any server. Create memes, add captions, or apply watermarks with full control over styling and positioning.',
      'Use quick templates for common styles: Meme (large text at top), Subtitle (bottom text with background), or Corner Tag (small watermark). Or customize everything: font size, color, stroke/outline, and background strip.',
      'Position text anywhere with the 9-position grid. All processing happens locally using FFmpeg WebAssembly, keeping your content private. Export to GIF, WebP, or MP4.',
    ],
    features: [
      'Add text overlays to GIF, WebP, APNG, or MP4.',
      'Quick templates: Meme, Subtitle, Corner Tag.',
      '9-position alignment for text placement.',
      'Customizable font size, color, and stroke/outline.',
      'Optional semi-transparent background strip.',
      'Multi-line text support.',
      'Output to GIF, WebP, or MP4 format.',
      'No watermark, no signup, 100% browser-side.',
    ],
    faq: [
      { q: 'Can I add multiple lines of text?', a: 'Yes, press Enter in the text box to create multiple lines. All lines will be positioned together.' },
      { q: 'Why does text look blurry?', a: 'Try increasing font size or stroke width. WebP output typically produces sharper results than GIF.' },
      { q: 'Are non-English characters supported?', a: 'Basic international characters work. Due to FFmpeg WASM font limitations, some special characters may not display correctly.' },
      { q: 'Can I add multiple text layers?', a: 'Currently the tool supports one text layer. For multiple layers, process the file multiple times.' },
      { q: 'Do you add a watermark?', a: 'No. Exports are completely watermark-free.' },
      { q: 'Are files uploaded to a server?', a: 'No. All processing happens locally in your browser.' },
      { q: 'Why is processing slow for large files?', a: 'Large GIFs or long videos require more processing time. Consider using shorter clips or smaller dimensions.' },
    ],
    relatedLinks: related('/add-text-to-gif'),
    ogImage: defaultOg,
  },
};
